[build]
include_ext = ["go", "tmpl", "templ", "html", "json"]
exclude_regex = [".*_templ.go", ".*.html"]
pre_cmd = ["go generate ."]
cmd = "go build -o ./tmp/main dev.go"
send_interrupt = true
stop_on_error = true

[proxy]
enabled = false
app_port = 8081
proxy_port = 8082

[log]
# Only show main log (silences watcher, build, runner)
main_only = true
